The error suggests that the JRC climate data API is returning a HTTP 400 (Bad Request) response. This commonly happens due to rate limiting, invalid coordinates, or API issues. Here's a solution to make the climate data loading more robust:

/Users/ykk/Documents/GitHub/AdOpT-NET0_XiaoY/.venv/bin/python /Users/ykk/Documents/GitHub/AdOpT-NET0_XiaoY/southern_europe/main.py
Files already exist: northern_italy_case/Topology.json northern_italy_case/ConfigModel.json
Importing Climate Data...
Importing Climate Data successful
Importing Climate Data...
Importing Climate Data successful
Importing Climate Data...
Importing Climate Data successful
Importing Climate Data...
Importing Climate Data successful
Importing Climate Data...
Importing Climate Data successful
Importing Climate Data...
Importing Climate Data successful
Importing Climate Data...
Importing Climate Data successful
Importing Climate Data...
Importing Climate Data successful
Importing Climate Data...
Importing Climate Data successful
Importing Climate Data...
Importing Climate Data successful
Importing Climate Data...
Importing Climate Data successful
Importing Climate Data...
Importing Climate Data successful
Importing Climate Data...
Importing Climate Data successful
Importing Climate Data...
Traceback (most recent call last):
  File "/Users/ykk/Documents/GitHub/AdOpT-NET0_XiaoY/southern_europe/main.py", line 150, in <module>
    adopt.load_climate_data_from_api(input_data_path)
  File "/Users/ykk/Documents/GitHub/AdOpT-NET0_XiaoY/adopt_net0/data_preprocessing/data_loading.py", line 57, in load_climate_data_from_api
    data = import_jrc_climate_data(lon, lat, year, alt)
  File "/Users/ykk/Documents/GitHub/AdOpT-NET0_XiaoY/adopt_net0/data_preprocessing/data_loading.py", line 297, in import_jrc_climate_data
    raise Exception(response)
Exception: <Response [400]>

Process finished with exit code 1
